version: "3"
services:
    hub:
        image: selenium/hub
        container_name: hub
        ports: 
            - "4444:4444"
        volumes:
            - /DockerSample/DotNet/Resources:/DockerSample/DotNet/Resources
    chrome:
        image: selenium/node-chrome
        depends_on: 
            - hub
        environment:
            - SE_EVENT_BUS_HOST=hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        shm_size: '2gb'
    firefox:
        image: selenium/node-firefox
        depends_on: 
            - hub
        environment:
            - SE_EVENT_BUS_HOST=hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        shm_size: '2gb'
    edge:
        image: selenium/node-edge
        depends_on: 
            - hub
        environment:
            - SE_EVENT_BUS_HOST=hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        shm_size: '2gb'
    
    
    
    #dotnetsdk:
        #image: mcr.microsoft.com/dotnet/sdk:3.1
        #entrypoint: "dotnet test DemoQATests.csproj"
        #entrypoint: "ping http://172.19.0.2.4444"
        #working_dir: /a/b/c
        #volumes:
         #   - C:/DockerSample/DotNet:/a/b/c
        #depends_on:
         #   - selenium